"""GitHub traffic rollup for the BGI repos.

Pulls clone counts, view counts, stars, and recent issue/PR activity for
ahmedxuhri/bigindexer and ahmedxuhri/bigindexer-pr-risk-bot via the gh
CLI (assumed authenticated as ahmedxuhri per the project's commit
policy). Writes a markdown rollup to output/rollups/github_traffic.md.

The traffic API only returns the trailing 14 days, so this script is
designed to be run on a cadence (weekly is fine) — the output snapshots
the current 14-day window. Long-term trends are out of scope; this is
adoption signal, not a dashboard.

Usage:
    python3 scripts/rollups/github_traffic.py
    python3 scripts/rollups/github_traffic.py --out output/rollups/github_traffic.md
"""
from __future__ import annotations

import argparse
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path

REPOS = [
    "ahmedxuhri/bigindexer",
    "ahmedxuhri/bigindexer-pr-risk-bot",
]


def _gh(args: list[str]) -> dict | list | None:
    try:
        result = subprocess.run(
            ["gh", *args],
            capture_output=True, text=True, timeout=30,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired) as exc:
        print(f"  ! gh call failed: {exc}")
        return None
    if result.returncode != 0:
        print(f"  ! gh returned {result.returncode}: {result.stderr.strip()}")
        return None
    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError:
        return None


def _repo_summary(repo: str) -> dict:
    """Pull a snapshot of public + traffic metrics for one repo."""
    info: dict[str, object] = {"repo": repo}

    public = _gh(["api", f"repos/{repo}"])
    if isinstance(public, dict):
        info["stargazers"] = public.get("stargazers_count", 0)
        info["forks"] = public.get("forks_count", 0)
        info["open_issues"] = public.get("open_issues_count", 0)
        info["subscribers"] = public.get("subscribers_count", 0)
    else:
        info["stargazers"] = info["forks"] = info["open_issues"] = info["subscribers"] = None

    clones = _gh(["api", f"repos/{repo}/traffic/clones"])
    if isinstance(clones, dict):
        info["clones_14d"] = clones.get("count", 0)
        info["unique_cloners_14d"] = clones.get("uniques", 0)
    else:
        info["clones_14d"] = info["unique_cloners_14d"] = None

    views = _gh(["api", f"repos/{repo}/traffic/views"])
    if isinstance(views, dict):
        info["views_14d"] = views.get("count", 0)
        info["unique_visitors_14d"] = views.get("uniques", 0)
    else:
        info["views_14d"] = info["unique_visitors_14d"] = None

    referrers = _gh(["api", f"repos/{repo}/traffic/popular/referrers"])
    info["top_referrers"] = referrers if isinstance(referrers, list) else []

    paths = _gh(["api", f"repos/{repo}/traffic/popular/paths"])
    info["top_paths"] = paths if isinstance(paths, list) else []

    return info


def _format_markdown(snapshots: list[dict]) -> str:
    now = datetime.now(timezone.utc).isoformat(timespec="seconds")
    lines = [
        "# GitHub traffic rollup",
        "",
        f"_Snapshot generated {now}. Traffic API window is the trailing 14 days._",
        "",
        "| Repo | Stars | Forks | Subs | Open issues | Clones (14d) | Unique cloners | Views (14d) | Unique visitors |",
        "|------|------:|------:|-----:|------------:|-------------:|---------------:|------------:|----------------:|",
    ]
    for s in snapshots:
        def fmt(v):
            return "—" if v is None else str(v)
        lines.append(
            f"| `{s['repo']}` | {fmt(s.get('stargazers'))} | {fmt(s.get('forks'))} | "
            f"{fmt(s.get('subscribers'))} | {fmt(s.get('open_issues'))} | "
            f"{fmt(s.get('clones_14d'))} | {fmt(s.get('unique_cloners_14d'))} | "
            f"{fmt(s.get('views_14d'))} | {fmt(s.get('unique_visitors_14d'))} |"
        )
    lines.append("")

    for s in snapshots:
        lines.append(f"## `{s['repo']}` — top referrers / paths (14d)")
        lines.append("")
        if s.get("top_referrers"):
            lines.append("**Referrers:**")
            for r in s["top_referrers"][:10]:
                lines.append(
                    f"- `{r.get('referrer', '?')}` — "
                    f"{r.get('count', 0)} views / {r.get('uniques', 0)} unique"
                )
            lines.append("")
        if s.get("top_paths"):
            lines.append("**Paths:**")
            for p in s["top_paths"][:10]:
                lines.append(
                    f"- `{p.get('path', '?')}` — "
                    f"{p.get('count', 0)} views / {p.get('uniques', 0)} unique"
                )
            lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("_Generated by `scripts/rollups/github_traffic.py`._")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="output/rollups/github_traffic.md",
                    help="Output markdown path")
    ap.add_argument("--repos", default=",".join(REPOS),
                    help="Comma-separated GitHub slugs")
    args = ap.parse_args()

    repos = [r.strip() for r in args.repos.split(",") if r.strip()]
    snapshots: list[dict] = []
    for repo in repos:
        print(f"  · pulling {repo}")
        snapshots.append(_repo_summary(repo))

    md = _format_markdown(snapshots)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(md)
    print(f"  → wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
