FROM node:18-alpine

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --omit=dev

COPY server.js public ./
EXPOSE 3000

# Redirect stdout/stderr to ensure logs are captured
CMD ["node", "server.js"]
